### ISSUE TITLE
First name is a known prefix

### ISSUE THREAD

**Issue by rlsjr** [aeshirey/NameParserSharp#20]
I greatly appreciate your project.  In the data I am using I have a Mr. Del Richards.  The last name returns Del Richards as del is listed in prefixes. However, Del is his first name.  I am thinking that it could treat the prefix as the first name if there is not a first name, but there would be times no first name could be included.  Any thoughts how to parse this one name correctly?

**Comment by Kaotic3** [comment]
I am encountering the same problem.

I tried to go into the base file and amend it to remove reference to the prefix that was actually a name and the file is read-only.  My knowledge on using Visual Studio 2022 is a bit limited - and I have no idea if this is done on your end to protect the project or something that Visual Studio is doing?

For the poster above, if you go to your program, hold down CTRL - and then click on HumanName the class variable - it should open up the NameParser.HumanName file and there you will find a list of all the prefixes, titles, suffixes that are being used - "del" is in prefixes.  You may be able to amend them there, although I couldn't.

**Comment by rlsjr** [comment]
Kaotic3, I do not want the prefix removed; it is valid. Removing it would incorrectly impact other names.  We need a way to determine when a prefix is a first name instead of a prefix.

**Comment by aeshirey** [comment]
I agree that "del" shouldn't be removed from the prefixes, but handling this case isn't clear-cut. The input "Mr. Del Richards" could be reasonably understood to be `Title First Last` or `Title LastPrefix Last`, so I see a few possibilities here:

* Make prefix parsing case sensitive because surname prefixes are sometimes lowercase (eg, [Guido van Rossum](https://en.wikipedia.org/wiki/Guido_van_Rossum)). Unfortunately, this isn't always the case (eg, [Oscar De La Hoya](https://en.wikipedia.org/wiki/Oscar_De_La_Hoya)); plus, making this library suddenly case aware seems like a breaking change.
*  Add logic to specifically handle the case when you have `Title + LastPrefix + Last` where `LastPrefix` is a single token. This would correctly handle "Mr. Del Richards" but would also incorrectly parse "Mr. Van Rossum". Also breaking.
* Detect this case and parse it twice, yielding the alternate in the `HumanName.AdditionalName` field. This might be a bit complex to handle and would kick the disambiguation to the caller. What might the 'correct' handling of "Mr. Del Richards and Mr. Van Rossum" be? You'd get four names back and you'd have to decide yourself how to handle the results.
* Add in a ctor argument that dictates how parsing should be handled, eg:
    ```csharp
    var del = new HumanName("Mr. Del Richards", Prefer.FirstOverPrefix); // first = "Del", last = "Richards"
    var van = new HumanName("Mr. Van Rossum",   Prefer.PrefixOverFirst); // first = "",    last = "Van Rossum"
    ```
* Expose the configuration lists so the caller can modify them as desired. If you want to remove "del" from the list of `Prefixes`, that should fix the problem for you, but you'll need to know that's what you want.

The last two options seem the least bad. It still requires the caller disambiguate, but they should know their data better than I do, and I can't think of any better way to handle it.

**Comment by rlsjr** [comment]
I would not modify the configuration lists.  With my data removing the Del prefix would fix the one record but cause two others to be incorrect.  I know in my data, I should always have a first name so that a PreferFirstOverPrefix could work.  But how would Mr. David M Del Rio be parsed if PreferFirstOverPrefix is selected?  I am sure you are a lot more knowledgeable about names than I am.

**Comment by aeshirey** [comment]
The ability to modify configuration now exists (in the source code, not yet in the NuGet package), but you're not obligated to use this.

I'm also adding in a `Prefer` enum that should do what you want:

```csharp
public void FirstNameIsPrefix()
{
    // Default behavior
    var parsed_prefix = new HumanName("Mr. Del Richards");
    Assert.AreEqual(parsed_prefix.Title, "Mr.");
    Assert.AreEqual(parsed_prefix.First, "");
    Assert.AreEqual(parsed_prefix.Last, "Del Richards");
    Assert.AreEqual(parsed_prefix.LastPrefixes, "Del");

    // A single prefix should be treated as a first name when no first exists
    var parsed_first = new HumanName("Mr. Del Richards", Prefer.FirstOverPrefix);
    Assert.AreEqual(parsed_first.Title, "Mr.");
    Assert.AreEqual(parsed_first.First, "Del");
    Assert.AreEqual(parsed_first.Last, "Richards");
    Assert.AreEqual(parsed_first.LastPrefixes, "");
}
```

Does this fit your needs?

**Comment by rlsjr** [comment]
I think that would fit my requirements.   Thank you.

**Comment by aeshirey** [comment]
The new version is [available on nuget](https://www.nuget.org/packages/NameParserSharp/1.5.0). You should be able to install with `Install-Package NameParserSharp -Version 1.5.0`

**Comment by rlsjr** [comment]
Thank you so much for your help. Update works great and all names are parsed as expected.
